---
name: "Setup Workspace"
description: "Configure Go and prepare the workspace"

runs:
  using: composite
  steps:
    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.21.4"
    - name: Install Just
      uses: extractions/setup-just@v2
    - name: Install Go modules
      shell: bash
      run: |
        just tidy
